# Generated by Django 5.2 on 2025-04-06 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColocationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Studio', 'Studio'), ('Loft', 'Loft'), ('Chambre', 'Chambre'), ('Autre', 'Autre')], max_length=255)),
                ('furnished', models.CharField(choices=[('Meublé', 'Meublé'), ('Non meublé', 'Non meublé')], max_length=255)),
                ('surface', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('rent', models.PositiveIntegerField()),
                ('charges', models.PositiveIntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autorisation', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colocation_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColocationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colocation_photos/')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app1.colocationoffer')),
            ],
        ),
    ]
