# Generated by Django 5.2 on 2025-04-11 11:01

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_colocationoffer_colocationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pays',
            field=django_countries.fields.CountryField(default='MA', max_length=2),
        ),
    ]
