# Generated by Django 5.2 on 2025-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customuser_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
