# Generated by Django 5.2 on 2025-04-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_customuser_adress_customuser_code_postale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='code_postale',
            new_name='code_postal',
        ),
    ]
