# Generated by Django 5.2 on 2025-04-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_code_postale_customuser_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
