# Generated by Django 5.2 on 2025-04-12 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_chatmessage_session_remove_chatsession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app1.colocationoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('offer', 'user')},
            },
        ),
    ]
