# Generated by Django 5.2 on 2025-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_like_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationoffer',
            name='location_name',
            field=models.CharField(default='Location undefined', max_length=255),
        ),
    ]
