# Generated by Django 5.2 on 2025-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_colocationoffer_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
