# Generated by Django 5.2 on 2025-04-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colocationoffer',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='colocationoffer',
            name='code_postal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colocationoffer',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='colocationoffer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.city'),
        ),
    ]
