# Generated by Django 5.2 on 2025-04-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_customuser_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Sex',
            new_name='genre',
        ),
    ]
