# Generated by Django 5.2 on 2025-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_sex_customuser_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Etudiant', 'Etudiant'), ('Salarié', 'Salarié')], max_length=255, null=True),
        ),
    ]
