# Generated by Django 5.2 on 2025-04-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colocationoffer',
            name='charges',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colocationoffer',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
