# Generated by Django 5.2 on 2025-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_colocationoffer_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationoffer',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Refusé', 'Refusé'), ('En attente', 'En attente'), ('Fini', 'Fini')], default='En attente', max_length=255),
        ),
    ]
