# Generated by Django 5.2 on 2025-04-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_colocationoffer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Visiteur', 'Visiteur'), ('Etudiant', 'Etudiant'), ('Entrepreneur', 'Entrepreneur')], max_length=255, null=True),
        ),
    ]
