# Generated by Django 5.2 on 2025-04-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Visiteur', 'Visiteur'), ('Etudiant', 'Etudiant'), ('Entrepreneur', 'Entrepreneur')], default='Visiteur', max_length=255),
        ),
    ]
