# Generated by Django 5.2 on 2025-04-16 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_customuser_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colocationoffer',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='elevator',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='colocationoffer',
            name='title',
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Studio', 'Studio'), ('Loft', 'Loft'), ('Chambre', 'Chambre'), ('Autre', 'Autre')], max_length=255)),
                ('furnished', models.CharField(choices=[('Meublé', 'Meublé'), ('Non meublé', 'Non meublé')], max_length=255)),
                ('surface', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('code_postal', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(default='Location undefined', max_length=255)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='colocationoffer',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='app1.house'),
        ),
    ]
