# Generated by Django 5.2 on 2025-04-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_thread_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
