# Generated by Django 5.2 on 2025-04-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
