# Generated by Django 5.2 on 2025-04-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_thread_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='etudiant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('universite', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau_scolaire', models.CharField(blank=True, choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Docotorat', 'Doctorat')], max_length=255, null=True)),
                ('bourse', models.BooleanField(default=False)),
                ('montant_bourse', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('job_etudiant', models.BooleanField(default=False)),
                ('job_etudiant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_etudiant_revenu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenu_mensuel_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
