# Generated by Django 5.2 on 2025-04-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Visiteur', 'Visiteur'), ('Étudiant', 'Étudiant'), ('Entrepreneur', 'Entrepreneur')], default='Visiteur', max_length=255),
        ),
    ]
