# Generated by Django 5.2 on 2025-04-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_customuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='entrepreneur', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('societé', models.CharField(blank=True, max_length=255, null=True)),
                ('société_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('APPROUVÉE', 'APPROUVÉE'), ('REFUSÉE', 'REFUSÉE')], default='EN ATTENTE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='réglamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('En cours de traitement', 'En cours de traitement'), ('Rejetée', 'Rejetée'), ('Résolue', 'Résolue')], default='En cours de traitement', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='réclameur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
