# Generated by Django 5.2 on 2025-04-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_entrepreneur_candidature_réglamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='app1.colocationoffer'),
        ),
    ]
