# Generated by Django 5.2 on 2025-05-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_candidature_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocationoffer',
            name='nombre_personne',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
