# Generated by Django 5.2 on 2025-05-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_notification_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
